services:
  app:
    container_name: uf_variation_app
    image: uf_variation_image
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
